// ATLAS ENGLISH - Complete Curriculum (78 Topics, 5 Levels, 1560 Questions)

export const LEVELS = ['A1', 'A2', 'B1', 'B2', 'C1'];

export const LESSON_BANK = [
  // ========== A1 (18 TEMAS) ==========
  {
    level: 'A1',
    id: 1,
    title: 'Verbo "to be" (presente)',
    description: 'El verbo más fundamental. AM (I), IS (he/she/it), ARE (you/we/they).',
    questions: [
      {q: "I ___ a student.", o: ["am", "is", "are"], c: 0},
      {q: "He ___ from Panama.", o: ["am", "is", "are"], c: 1},
      {q: "We ___ friends.", o: ["am", "is", "are"], c: 2},
      {q: "She ___ happy.", o: ["am", "is", "are"], c: 1},
      {q: "They ___ teachers.", o: ["am", "is", "are"], c: 2},
      {q: "You ___ smart.", o: ["am", "is", "are"], c: 2},
      {q: "It ___ a cat.", o: ["am", "is", "are"], c: 1},
      {q: "I ___ tired.", o: ["am", "is", "are"], c: 0},
      {q: "Mary ___ in the classroom.", o: ["am", "is", "are"], c: 1},
      {q: "My parents ___ at home.", o: ["am", "is", "are"], c: 2},
      {q: "The dog ___ brown.", o: ["am", "is", "are"], c: 1},
      {q: "I ___ a doctor.", o: ["am", "is", "are"], c: 0},
      {q: "They ___ students.", o: ["am", "is", "are"], c: 2},
      {q: "You ___ my friend.", o: ["am", "is", "are"], c: 2},
      {q: "She ___ beautiful.", o: ["am", "is", "are"], c: 1},
      {q: "We ___ at school.", o: ["am", "is", "are"], c: 2},
      {q: "It ___ cold today.", o: ["am", "is", "are"], c: 1},
      {q: "He ___ an engineer.", o: ["am", "is", "are"], c: 1},
      {q: "I ___ hungry.", o: ["am", "is", "are"], c: 0},
      {q: "The sky ___ blue.", o: ["am", "is", "are"], c: 1}
    ]
  },
  {
    level: 'A1',
    id: 2,
    title: 'Artículos a / an / the',
    description: 'Usa "a" antes de consonantes, "an" antes de vocales, "the" para cosas específicas.',
    questions: [
      {q: "___ apple is red.", o: ["A", "An", "The"], c: 1},
      {q: "I want ___ sandwich.", o: ["a", "an", "the"], c: 0},
      {q: "___ cat on the table is mine.", o: ["A", "An", "The"], c: 2},
      {q: "She is ___ teacher.", o: ["a", "an", "the"], c: 0},
      {q: "He plays ___ guitar.", o: ["a", "an", "the"], c: 0},
      {q: "There is ___ elephant in the zoo.", o: ["a", "an", "the"], c: 1},
      {q: "I love ___ music.", o: ["a", "an", "the"], c: 2},
      {q: "She has ___ orange.", o: ["a", "an", "the"], c: 1},
      {q: "___ sun is hot.", o: ["A", "An", "The"], c: 2},
      {q: "Do you have ___ pen?", o: ["a", "an", "the"], c: 0},
      {q: "I live in ___ house.", o: ["a", "an", "the"], c: 0},
      {q: "She drinks ___ milk.", o: ["a", "an", "the"], c: 0},
      {q: "He is ___ actor.", o: ["a", "an", "the"], c: 0},
      {q: "___ umbrella is black.", o: ["A", "An", "The"], c: 2},
      {q: "I see ___ bird.", o: ["a", "an", "the"], c: 0},
      {q: "This is ___ interesting book.", o: ["a", "an", "the"], c: 0},
      {q: "She goes to ___ school every day.", o: ["a", "an", "the"], c: 2},
      {q: "There is ___ egg on the plate.", o: ["a", "an", "the"], c: 0},
      {q: "I need ___ new shirt.", o: ["a", "an", "the"], c: 0},
      {q: "___ president is important.", o: ["A", "An", "The"], c: 2}
    ]
  },
  {
    level: 'A1',
    id: 3,
    title: 'Pronombres personales sujeto',
    description: 'I, you, he, she, it, we, they como sujeto de la oración.',
    questions: [
      {q: "___ am a student.", o: ["I", "You", "He"], c: 0},
      {q: "___ are my friends.", o: ["It", "They", "She"], c: 1},
      {q: "___ is from England.", o: ["We", "She", "You"], c: 1},
      {q: "___ are in the park.", o: ["I", "We", "He"], c: 1},
      {q: "___ speaks Spanish.", o: ["I", "He", "We"], c: 1},
      {q: "___ plays football.", o: ["You", "It", "They"], c: 1},
      {q: "___ like chocolate.", o: ["I", "She", "It"], c: 0},
      {q: "___ is a doctor.", o: ["You", "He", "We"], c: 1},
      {q: "___ have a dog.", o: ["She", "I", "It"], c: 1},
      {q: "___ works here.", o: ["We", "She", "You"], c: 1},
      {q: "___ go to school every day.", o: ["It", "They", "He"], c: 1},
      {q: "___ am happy.", o: ["You", "I", "She"], c: 1},
      {q: "___ is nice.", o: ["I", "She", "We"], c: 1},
      {q: "___ are smart.", o: ["He", "They", "She"], c: 1},
      {q: "___ watch movies together.", o: ["We", "He", "It"], c: 0},
      {q: "___ speaks English well.", o: ["I", "You", "She"], c: 2},
      {q: "___ live in the city.", o: ["She", "I", "They"], c: 2},
      {q: "___ is my brother.", o: ["He", "They", "We"], c: 0},
      {q: "___ have a cat.", o: ["You", "It", "She"], c: 0},
      {q: "___ eats pizza.", o: ["We", "He", "I"], c: 1}
    ]
  },
  {
    level: 'A1',
    id: 4,
    title: 'Sustantivos: singular y plural',
    description: 'Formación regular del plural: añadir -s o -es. Plurales irregulares comunes.',
    questions: [
      {q: "One cat, two ___.", o: ["cat", "cats", "cates"], c: 1},
      {q: "One box, two ___.", o: ["box", "boxes", "boxs"], c: 1},
      {q: "One child, two ___.", o: ["child", "childs", "children"], c: 2},
      {q: "One man, two ___.", o: ["man", "mans", "men"], c: 2},
      {q: "One book, two ___.", o: ["book", "books", "bookes"], c: 1},
      {q: "One class, two ___.", o: ["class", "classs", "classes"], c: 2},
      {q: "One woman, two ___.", o: ["woman", "womans", "women"], c: 2},
      {q: "One tooth, two ___.", o: ["tooth", "tooths", "teeth"], c: 2},
      {q: "One mouse, two ___.", o: ["mouse", "mouses", "mice"], c: 2},
      {q: "One bird, two ___.", o: ["bird", "birds", "birdes"], c: 1},
      {q: "One foot, two ___.", o: ["foot", "foots", "feet"], c: 2},
      {q: "One house, two ___.", o: ["house", "houses", "housis"], c: 1},
      {q: "One person, two ___.", o: ["person", "persons", "people"], c: 2},
      {q: "One bus, two ___.", o: ["bus", "buss", "buses"], c: 2},
      {q: "One pencil, two ___.", o: ["pencil", "pencils", "penciles"], c: 1},
      {q: "One glass, two ___.", o: ["glass", "glasss", "glasses"], c: 2},
      {q: "One potato, two ___.", o: ["potato", "potatos", "potatoes"], c: 2},
      {q: "One goose, two ___.", o: ["goose", "gooses", "geese"], c: 2},
      {q: "One flower, two ___.", o: ["flower", "flowers", "floweres"], c: 1},
      {q: "One sheep, two ___.", o: ["sheep", "sheeps", "sheep"], c: 2}
    ]
  },
  {
    level: 'A1',
    id: 5,
    title: 'Adjetivos básicos (posición)',
    description: 'Adjetivos descriptivos antes del sustantivo: big, small, happy, sad, red, etc.',
    questions: [
      {q: "She is a ___ girl.", o: ["girl beautiful", "beautiful girl", "girl beauty"], c: 1},
      {q: "I have a ___ car.", o: ["red big", "big red", "red car"], c: 1},
      {q: "That is a ___ book.", o: ["interesting", "book interesting", "very interesting"], c: 0},
      {q: "The ___ house is expensive.", o: ["old", "houses old", "the old"], c: 0},
      {q: "I like ___ music.", o: ["good", "good music", "music good"], c: 1},
      {q: "She wears ___ shoes.", o: ["yellow", "shoes yellow", "yellow shoes"], c: 2},
      {q: "He has a ___ dog.", o: ["small cute", "cute small", "small"], c: 2},
      {q: "This is a ___ movie.", o: ["exciting", "movie exciting", "the exciting"], c: 0},
      {q: "The ___ weather is nice.", o: ["today", "sunny", "sun"], c: 1},
      {q: "I see a ___ tree.", o: ["tall and green", "green tall", "tall"], c: 1},
      {q: "She has ___ eyes.", o: ["blue", "eyes blue", "the blue"], c: 0},
      {q: "The ___ box is heavy.", o: ["big", "box big", "heavy big"], c: 0},
      {q: "That's a ___ idea.", o: ["bad", "good idea", "ideas good"], c: 0},
      {q: "I drink ___ tea.", o: ["hot", "tea hot", "the hot"], c: 0},
      {q: "The ___ children play outside.", o: ["happy", "child happy", "happy childrens"], c: 0},
      {q: "He has a ___ voice.", o: ["soft", "voice soft", "soft voice"], c: 2},
      {q: "This is a ___ problem.", o: ["difficult", "problems difficult", "difficulties"], c: 0},
      {q: "The ___ sky is beautiful.", o: ["blue", "skies blue", "the beautiful"], c: 0},
      {q: "I love ___ flowers.", o: ["colorful", "flowers colorful", "colors"], c: 0},
      {q: "The ___ road is long.", o: ["long", "roads long", "the long"], c: 0}
    ]
  },
  {
    level: 'A1',
    id: 6,
    title: 'Pronombres y adjetivos posesivos',
    description: 'My, your, his, her, its, our, their. Pronombres: mine, yours, his, hers, ours, theirs.',
    questions: [
      {q: "This is ___ book.", o: ["my", "me", "I"], c: 0},
      {q: "That is ___ house.", o: ["his", "him", "he"], c: 0},
      {q: "These are ___ shoes.", o: ["her", "hers", "she"], c: 0},
      {q: "Is this ___ pen?", o: ["your", "you", "yours"], c: 0},
      {q: "The cat licks ___ paws.", o: ["its", "it", "it's"], c: 0},
      {q: "We love ___ school.", o: ["our", "ours", "we"], c: 0},
      {q: "They lost ___ keys.", o: ["their", "theirs", "them"], c: 0},
      {q: "This is mine. That is ___.", o: ["yours", "your", "you"], c: 0},
      {q: "The pen is ___.", o: ["hers", "her", "she"], c: 0},
      {q: "These books are ___.", o: ["ours", "our", "we"], c: 0},
      {q: "The house is ___.", o: ["theirs", "their", "them"], c: 0},
      {q: "I see ___ car in the street.", o: ["his", "him", "he"], c: 0},
      {q: "She has ___ phone with her.", o: ["her", "hers", "she"], c: 0},
      {q: "They enjoy ___ time together.", o: ["their", "theirs", "them"], c: 0},
      {q: "Is this ___ book?", o: ["my", "mine", "me"], c: 0},
      {q: "The dog plays with ___ toys.", o: ["its", "it", "it's"], c: 0},
      {q: "We help ___ friends.", o: ["our", "ours", "we"], c: 0},
      {q: "He shows ___ skills.", o: ["his", "him", "he"], c: 0},
      {q: "I like ___ color.", o: ["your", "you", "yours"], c: 0},
      {q: "The painting is ___.", o: ["theirs", "their", "them"], c: 0}
    ]
  },
  {
    level: 'A1',
    id: 7,
    title: 'Presente simple',
    description: 'Acciones habituales y hechos generales. Estructura: sujeto + verbo base (+ s en tercera persona).',
    questions: [
      {q: "I ___ English.", o: ["speak", "speaks", "speaking"], c: 0},
      {q: "She ___ coffee every morning.", o: ["drink", "drinks", "drinking"], c: 1},
      {q: "They ___ in a house.", o: ["live", "lives", "living"], c: 0},
      {q: "He ___ to school.", o: ["go", "goes", "going"], c: 1},
      {q: "We ___ football on Sundays.", o: ["play", "plays", "playing"], c: 0},
      {q: "It ___ at night.", o: ["sleep", "sleeps", "sleeping"], c: 1},
      {q: "I ___ breakfast every day.", o: ["eat", "eats", "eating"], c: 0},
      {q: "She ___ music.", o: ["like", "likes", "liking"], c: 1},
      {q: "They ___ from Spain.", o: ["come", "comes", "coming"], c: 0},
      {q: "He ___ his car.", o: ["wash", "washes", "washing"], c: 1},
      {q: "You ___ English well.", o: ["speak", "speaks", "speaking"], c: 0},
      {q: "The sun ___ in the east.", o: ["rise", "rises", "rising"], c: 1},
      {q: "I ___ my homework.", o: ["do", "does", "doing"], c: 0},
      {q: "She ___ a teacher.", o: ["work", "works", "working"], c: 1},
      {q: "They ___ movies.", o: ["watch", "watches", "watching"], c: 0},
      {q: "He ___ books.", o: ["read", "reads", "reading"], c: 1},
      {q: "We ___ in an apartment.", o: ["live", "lives", "living"], c: 0},
      {q: "She ___ her bike.", o: ["ride", "rides", "riding"], c: 1},
      {q: "I ___ my teeth twice a day.", o: ["brush", "brushes", "brushing"], c: 0},
      {q: "They ___ on the beach.", o: ["walk", "walks", "walking"], c: 0}
    ]
  },
  {
    level: 'A1',
    id: 8,
    title: 'Imperativo',
    description: 'Órdenes y instrucciones. Usa el verbo base sin sujeto.',
    questions: [
      {q: "___ the door!", o: ["Open", "Opens", "Opening"], c: 0},
      {q: "___ me your phone.", o: ["Give", "Gives", "Giving"], c: 0},
      {q: "___ sit down!", o: ["Please", "You", "Can you"], c: 0},
      {q: "___ your book!", o: ["Close", "Closes", "Closing"], c: 0},
      {q: "___ quiet!", o: ["Be", "Bes", "Being"], c: 0},
      {q: "___ your homework!", o: ["Do", "Does", "Doing"], c: 0},
      {q: "___ to the right.", o: ["Turn", "Turns", "Turning"], c: 0},
      {q: "___ me!", o: ["Help", "Helps", "Helping"], c: 0},
      {q: "___ the light!", o: ["Turn on", "Turns on", "Turning on"], c: 0},
      {q: "___ this medicine.", o: ["Take", "Takes", "Taking"], c: 0},
      {q: "___ water!", o: ["Drink", "Drinks", "Drinking"], c: 0},
      {q: "___ down!", o: ["Sit", "Sits", "Sitting"], c: 0},
      {q: "___ your teeth!", o: ["Brush", "Brushes", "Brushing"], c: 0},
      {q: "___ the window!", o: ["Open", "Opens", "Opening"], c: 0},
      {q: "___ your shoes!", o: ["Take off", "Takes off", "Taking off"], c: 0},
      {q: "___ here.", o: ["Wait", "Waits", "Waiting"], c: 0},
      {q: "___ to me.", o: ["Listen", "Listens", "Listening"], c: 0},
      {q: "___ careful!", o: ["Be", "Is", "Being"], c: 0},
      {q: "___ your voice!", o: ["Lower", "Lowers", "Lowering"], c: 0},
      {q: "___ my hand.", o: ["Hold", "Holds", "Holding"], c: 0}
    ]
  },
  {
    level: 'A1',
    id: 9,
    title: 'Números, fechas y hora',
    description: 'Números cardinales y ordinales. Cómo decir la fecha y la hora.',
    questions: [
      {q: "Three plus two equals ___.", o: ["five", "four", "six"], c: 0},
      {q: "Today is the ___ of May.", o: ["twenty-first", "twenty one", "the twenty-first"], c: 0},
      {q: "What time is it? It's ___.", o: ["3 o'clock", "3 o clock", "the 3 o'clock"], c: 0},
      {q: "I was born in 1990, so I am the ___ generation.", o: ["nineties", "the 1990s", "1990s born"], c: 0},
      {q: "She lives on ___ Street.", o: ["Fifth", "Five", "the Five"], c: 0},
      {q: "The book costs ___.", o: ["25 dollars", "$25", "25 dollar"], c: 1},
      {q: "They have ___ children.", o: ["three", "the three", "three of"], c: 0},
      {q: "It's ___ outside.", o: ["half past two", "two and half", "two half past"], c: 0},
      {q: "My birthday is ___ December.", o: ["on the 15th of", "in the 15th of", "the 15 December"], c: 0},
      {q: "He scored ___ goals.", o: ["ten", "the ten", "ten of"], c: 0},
      {q: "The meeting starts at ___.", o: ["9 a.m.", "9am", "nine morning"], c: 0},
      {q: "There are ___ days in a week.", o: ["seven", "the seven", "seven of"], c: 0},
      {q: "She is ___ years old.", o: ["twenty-five", "twenty five", "the twenty-five"], c: 0},
      {q: "They finished the race at ___.", o: ["quarter past four", "quarter to four", "quarter past the four"], c: 0},
      {q: "He was born on ___ 1985.", o: ["March 3rd", "3 March", "the 3 of March"], c: 1},
      {q: "The temperature is ___ degrees.", o: ["thirty", "the thirty", "thirty of"], c: 0},
      {q: "I arrive at ___.", o: ["6:30 p.m.", "6:30 pm", "6 30 evening"], c: 1},
      {q: "They have been married for ___ years.", o: ["twenty", "the twenty", "twenty of"], c: 0},
      {q: "The class ends at ___.", o: ["quarter to five", "quarter past five", "five and quarter"], c: 0},
      {q: "She works from ___ to ___.", o: ["9 to 5", "9 until 5", "9 a.m. to 5 p.m."], c: 2}
    ]
  },
  {
    level: 'A1',
    id: 10,
    title: 'Preposiciones de lugar y tiempo básicas',
    description: 'in, on, at, under, behind, between, before, after, during.',
    questions: [
      {q: "The book is ___ the table.", o: ["on", "at", "in"], c: 0},
      {q: "She lives ___ London.", o: ["in", "on", "at"], c: 0},
      {q: "The pen is ___ the box.", o: ["in", "on", "at"], c: 0},
      {q: "I'll meet you ___ 3 o'clock.", o: ["at", "in", "on"], c: 0},
      {q: "The picture is ___ the wall.", o: ["on", "in", "at"], c: 0},
      {q: "She goes to school ___ Monday.", o: ["on", "in", "at"], c: 0},
      {q: "The keys are ___ the door.", o: ["under", "on", "in"], c: 0},
      {q: "I was born ___ January.", o: ["in", "on", "at"], c: 0},
      {q: "The cat is ___ the bed.", o: ["under", "on", "in"], c: 2},
      {q: "He is sitting ___ me.", o: ["beside", "in", "on"], c: 0},
      {q: "The house is ___ the street.", o: ["on", "in", "at"], c: 0},
      {q: "She works ___ the hospital.", o: ["in", "on", "at"], c: 0},
      {q: "They arrived ___ the afternoon.", o: ["in", "on", "at"], c: 0},
      {q: "The bag is ___ the chair.", o: ["under", "on", "in"], c: 1},
      {q: "I usually eat breakfast ___ 7 a.m.", o: ["at", "in", "on"], c: 0},
      {q: "The flowers are ___ the vase.", o: ["in", "on", "at"], c: 0},
      {q: "She plays ___ the park.", o: ["in", "on", "at"], c: 0},
      {q: "The office is ___ the building.", o: ["in", "on", "at"], c: 0},
      {q: "He parked the car ___ the garage.", o: ["in", "on", "at"], c: 0},
      {q: "We meet ___ Fridays.", o: ["on", "in", "at"], c: 0}
    ]
  },
  {
    level: 'A1',
    id: 11,
    title: 'Adverbios de frecuencia básicos',
    description: 'always, usually, often, sometimes, rarely, never. Posición en la oración.',
    questions: [
      {q: "I ___ eat breakfast.", o: ["always", "never", "rarely"], c: 0},
      {q: "She ___ goes to the gym.", o: ["usually", "never", "rarely"], c: 0},
      {q: "They ___ watch movies on weekends.", o: ["sometimes", "always", "never"], c: 0},
      {q: "He ___ arrives late.", o: ["rarely", "always", "usually"], c: 0},
      {q: "I ___ drink coffee in the morning.", o: ["usually", "never", "rarely"], c: 0},
      {q: "She ___ cooks dinner at home.", o: ["always", "rarely", "never"], c: 0},
      {q: "They ___ visit their grandparents.", o: ["often", "always", "never"], c: 0},
      {q: "I ___ lie.", o: ["never", "always", "usually"], c: 0},
      {q: "She ___ smiles.", o: ["always", "never", "rarely"], c: 0},
      {q: "We ___ go to the beach in summer.", o: ["usually", "never", "rarely"], c: 0},
      {q: "He ___ forgets his keys.", o: ["often", "always", "never"], c: 0},
      {q: "I ___ sleep late on weekends.", o: ["sometimes", "always", "never"], c: 0},
      {q: "They ___ eat vegetables.", o: ["rarely", "always", "never"], c: 0},
      {q: "She ___ checks her email.", o: ["frequently", "always", "never"], c: 0},
      {q: "I ___ study before exams.", o: ["always", "never", "sometimes"], c: 2},
      {q: "He ___ makes mistakes.", o: ["sometimes", "always", "never"], c: 0},
      {q: "We ___ play chess together.", o: ["often", "always", "never"], c: 0},
      {q: "She ___ wears a hat.", o: ["rarely", "always", "never"], c: 0},
      {q: "I ___ feel tired after work.", o: ["usually", "never", "always"], c: 0},
      {q: "They ___ finish their homework.", o: ["always", "rarely", "never"], c: 0}
    ]
  },
  {
    level: 'A1',
    id: 12,
    title: 'Preguntas con palabras interrogativas simples',
    description: 'What, Where, When, Who, Why, How. Estructura básica.',
    questions: [
      {q: "___ is your name?", o: ["What", "Where", "Who"], c: 0},
      {q: "___ do you live?", o: ["Where", "What", "When"], c: 0},
      {q: "___ is your birthday?", o: ["When", "What", "Where"], c: 0},
      {q: "___ is your best friend?", o: ["Who", "What", "When"], c: 0},
      {q: "___ are you late?", o: ["Why", "What", "Where"], c: 0},
      {q: "___ old are you?", o: ["How", "What", "Where"], c: 0},
      {q: "___ is the weather today?", o: ["What", "Where", "When"], c: 0},
      {q: "___ are you going?", o: ["Where", "What", "Why"], c: 0},
      {q: "___ color is your car?", o: ["What", "Where", "When"], c: 0},
      {q: "___ is that?", o: ["Who", "What", "Where"], c: 0},
      {q: "___ do you like English?", o: ["Why", "What", "Where"], c: 0},
      {q: "___ many brothers do you have?", o: ["How", "What", "When"], c: 0},
      {q: "___ is your favorite food?", o: ["What", "Where", "When"], c: 0},
      {q: "___ do you work?", o: ["Where", "What", "When"], c: 0},
      {q: "___ tall is he?", o: ["How", "What", "Where"], c: 0},
      {q: "___ are they coming?", o: ["When", "What", "Where"], c: 0},
      {q: "___ does she study?", o: ["Why", "What", "How"], c: 0},
      {q: "___ is in the room?", o: ["Who", "What", "Where"], c: 0},
      {q: "___ is the capital of France?", o: ["What", "Where", "When"], c: 0},
      {q: "___ do you go to bed?", o: ["When", "What", "Where"], c: 0}
    ]
  },
  {
    level: 'A1',
    id: 13,
    title: 'There is / There are',
    description: 'Expresiones de existencia. Hay una / Hay.',
    questions: [
      {q: "___ a cat in the room.", o: ["There is", "There are", "Is there"], c: 0},
      {q: "___ five students in the class.", o: ["There are", "There is", "Are there"], c: 0},
      {q: "___ a book on the table.", o: ["There is", "There are", "Is there"], c: 0},
      {q: "___ apples in the basket.", o: ["There are", "There is", "Are there"], c: 0},
      {q: "___ water in the glass.", o: ["There is", "There are", "Is there"], c: 0},
      {q: "___ many people at the party.", o: ["There are", "There is", "Are there"], c: 0},
      {q: "Is ___ a pen in your bag?", o: ["there", "it", "that"], c: 0},
      {q: "Are ___ chairs in the living room?", o: ["there", "they", "those"], c: 0},
      {q: "___ three doors in the house.", o: ["There are", "There is", "Is there"], c: 0},
      {q: "___ a dog in the garden.", o: ["There is", "There are", "Is there"], c: 0},
      {q: "___ students at school today.", o: ["There are", "There is", "Are there"], c: 0},
      {q: "___ milk in the fridge.", o: ["There is", "There are", "Is there"], c: 0},
      {q: "___ flowers in the vase.", o: ["There are", "There is", "Are there"], c: 0},
      {q: "How many rooms are ___ in your house?", o: ["there", "it", "that"], c: 0},
      {q: "___ a problem with the car.", o: ["There is", "There are", "Is there"], c: 0},
      {q: "___ children playing outside.", o: ["There are", "There is", "Are there"], c: 0},
      {q: "___ windows in this room.", o: ["There are", "There is", "Is there"], c: 0},
      {q: "Is ___ sugar in the coffee?", o: ["there", "it", "that"], c: 0},
      {q: "___ two beaches near the city.", o: ["There are", "There is", "Is there"], c: 0},
      {q: "___ a good restaurant in this area.", o: ["There is", "There are", "Is there"], c: 0}
    ]
  },
  {
    level: 'A1',
    id: 14,
    title: 'Adjetivos demostrativos',
    description: 'This, that, these, those. Distancia y cantidad.',
    questions: [
      {q: "___ book is interesting.", o: ["This", "That", "These"], c: 0},
      {q: "___ cars are expensive.", o: ["Those", "This", "That"], c: 0},
      {q: "___ dog is brown.", o: ["That", "This", "Those"], c: 0},
      {q: "___ flowers are beautiful.", o: ["These", "This", "That"], c: 0},
      {q: "I like ___ house better.", o: ["this", "that", "these"], c: 0},
      {q: "___ shoes are new.", o: ["These", "This", "That"], c: 0},
      {q: "___ building is old.", o: ["That", "This", "These"], c: 0},
      {q: "___ people are my friends.", o: ["These", "This", "That"], c: 0},
      {q: "___ picture is nice.", o: ["This", "That", "These"], c: 0},
      {q: "___ trees are very tall.", o: ["Those", "This", "These"], c: 0},
      {q: "Do you want ___ coffee?", o: ["this", "that", "those"], c: 0},
      {q: "___ moment is important.", o: ["This", "That", "These"], c: 0},
      {q: "___ roads are dangerous.", o: ["Those", "This", "These"], c: 0},
      {q: "___ idea is good.", o: ["That", "This", "Those"], c: 0},
      {q: "___ animals are wild.", o: ["These", "This", "That"], c: 0},
      {q: "I prefer ___ color to that one.", o: ["this", "that", "these"], c: 0},
      {q: "___ movie was very good.", o: ["That", "This", "These"], c: 0},
      {q: "___ pens are broken.", o: ["These", "This", "That"], c: 0},
      {q: "___ time is difficult for everyone.", o: ["This", "That", "These"], c: 0},
      {q: "___ islands are beautiful.", o: ["Those", "This", "These"], c: 0}
    ]
  },
  {
    level: 'A1',
    id: 15,
    title: 'Can / Can\'t para habilidad y permiso',
    description: 'Capacidad y permiso. I can / I can\'t.',
    questions: [
      {q: "I ___ swim.", o: ["can", "can't", "cannot"], c: 0},
      {q: "She ___ speak French.", o: ["can", "can't", "cannot"], c: 0},
      {q: "He ___ play the guitar.", o: ["cannot", "can", "can't"], c: 0},
      {q: "We ___ speak English.", o: ["can", "can't", "cannot"], c: 0},
      {q: "They ___ drive.", o: ["can", "can't", "cannot"], c: 0},
      {q: "I ___ cook well.", o: ["can", "can't", "cannot"], c: 0},
      {q: "You ___ use the phone here.", o: ["can't", "can", "cannot"], c: 0},
      {q: "He ___ run very fast.", o: ["can", "can't", "cannot"], c: 0},
      {q: "She ___ sing.", o: ["can", "can't", "cannot"], c: 0},
      {q: "We ___ see the stars at night.", o: ["can", "can't", "cannot"], c: 0},
      {q: "They ___ find the way.", o: ["can't", "can", "cannot"], c: 0},
      {q: "___ you help me?", o: ["Can", "Cannot", "Can't"], c: 0},
      {q: "___ she dance?", o: ["Can", "Cannot", "Can't"], c: 0},
      {q: "I ___ go to the party.", o: ["can't", "can", "cannot"], c: 0},
      {q: "You ___ park here.", o: ["can't", "can", "cannot"], c: 0},
      {q: "He ___ pass the exam.", o: ["can", "can't", "cannot"], c: 0},
      {q: "She ___ ride a bike.", o: ["can", "can't", "cannot"], c: 0},
      {q: "They ___ understand.", o: ["can't", "can", "cannot"], c: 0},
      {q: "I ___ type very fast.", o: ["can", "can't", "cannot"], c: 0},
      {q: "___ you see me?", o: ["Can", "Cannot", "Can't"], c: 0}
    ]
  },
  {
    level: 'A1',
    id: 16,
    title: 'Presente continuo',
    description: 'Acciones en progreso ahora. Am/is/are + -ing.',
    questions: [
      {q: "I am ___ English right now.", o: ["speaking", "speak", "spoke"], c: 0},
      {q: "She is ___ a book.", o: ["reading", "read", "reads"], c: 0},
      {q: "They are ___ football.", o: ["playing", "play", "plays"], c: 0},
      {q: "He is ___ TV.", o: ["watching", "watch", "watches"], c: 0},
      {q: "We are ___ to the park.", o: ["going", "go", "goes"], c: 0},
      {q: "She is ___ dinner.", o: ["cooking", "cook", "cooks"], c: 0},
      {q: "I am ___ my homework.", o: ["doing", "do", "does"], c: 0},
      {q: "They are ___ in the pool.", o: ["swimming", "swim", "swims"], c: 0},
      {q: "You are ___ too fast.", o: ["driving", "drive", "drives"], c: 0},
      {q: "He is ___ a letter.", o: ["writing", "write", "writes"], c: 0},
      {q: "We are ___ music.", o: ["listening", "listen", "listens"], c: 0},
      {q: "She is ___ her phone.", o: ["using", "use", "uses"], c: 0},
      {q: "I am ___ breakfast.", o: ["eating", "eat", "eats"], c: 0},
      {q: "They are ___ in the garden.", o: ["working", "work", "works"], c: 0},
      {q: "He is ___ a shower.", o: ["taking", "take", "takes"], c: 0},
      {q: "You are ___ late.", o: ["arriving", "arrive", "arrives"], c: 0},
      {q: "We are ___ at the moment.", o: ["studying", "study", "studies"], c: 0},
      {q: "She is ___ the door.", o: ["opening", "open", "opens"], c: 0},
      {q: "I am ___ a new job.", o: ["starting", "start", "starts"], c: 0},
      {q: "They are ___ beautiful.", o: ["looking", "look", "looks"], c: 0}
    ]
  },
  {
    level: 'A1',
    id: 17,
    title: 'Pasado simple del verbo "to be"',
    description: 'was / were en pasado. I was, you were, he/she/it was, we/they were.',
    questions: [
      {q: "I ___ at home yesterday.", o: ["was", "were", "am"], c: 0},
      {q: "She ___ happy.", o: ["was", "were", "is"], c: 0},
      {q: "They ___ at the party.", o: ["were", "was", "are"], c: 0},
      {q: "He ___ a teacher.", o: ["was", "were", "is"], c: 0},
      {q: "We ___ in London last year.", o: ["were", "was", "are"], c: 0},
      {q: "You ___ late.", o: ["were", "was", "are"], c: 0},
      {q: "It ___ cold last winter.", o: ["was", "were", "is"], c: 0},
      {q: "The dog ___ brown.", o: ["was", "were", "is"], c: 0},
      {q: "I ___ not at work.", o: ["was", "were", "am"], c: 0},
      {q: "They ___ not ready.", o: ["were", "was", "are"], c: 0},
      {q: "___ you at school?", o: ["Were", "Was", "Are"], c: 0},
      {q: "___ she happy yesterday?", o: ["Was", "Were", "Is"], c: 0},
      {q: "He ___ in the car.", o: ["was", "were", "is"], c: 0},
      {q: "The students ___ tired.", o: ["were", "was", "are"], c: 0},
      {q: "I ___ seven years old in 2010.", o: ["was", "were", "am"], c: 0},
      {q: "She ___ a student then.", o: ["was", "were", "is"], c: 0},
      {q: "They ___ friends since childhood.", o: ["were", "was", "are"], c: 0},
      {q: "You ___ my best friend.", o: ["were", "was", "are"], c: 0},
      {q: "It ___ a beautiful day.", o: ["was", "were", "is"], c: 0},
      {q: "We ___ together all the time.", o: ["were", "was", "are"], c: 0}
    ]
  },
  {
    level: 'A1',
    id: 18,
    title: 'Pasado simple de verbos regulares',
    description: 'Verbos terminados en -ed. I worked, she studied, etc.',
    questions: [
      {q: "Yesterday, I ___ to the beach.", o: ["went", "go", "goes"], c: 0},
      {q: "She ___ the movie last night.", o: ["watched", "watch", "watches"], c: 0},
      {q: "They ___ in a house.", o: ["lived", "live", "lives"], c: 0},
      {q: "He ___ English yesterday.", o: ["studied", "study", "studies"], c: 0},
      {q: "We ___ football on Sunday.", o: ["played", "play", "plays"], c: 0},
      {q: "I ___ breakfast this morning.", o: ["ate", "eat", "eats"], c: 0},
      {q: "She ___ a book.", o: ["read", "reads", "reading"], c: 0},
      {q: "They ___ at the restaurant.", o: ["worked", "work", "works"], c: 0},
      {q: "He ___ the car.", o: ["washed", "wash", "washes"], c: 0},
      {q: "You ___ him last week.", o: ["saw", "see", "sees"], c: 0},
      {q: "I ___ my homework.", o: ["finished", "finish", "finishes"], c: 0},
      {q: "She ___ a new dress.", o: ["bought", "buy", "buys"], c: 0},
      {q: "They ___ at 10 a.m.", o: ["arrived", "arrive", "arrives"], c: 0},
      {q: "He ___ the window.", o: ["opened", "open", "opens"], c: 0},
      {q: "We ___ our friends.", o: ["visited", "visit", "visits"], c: 0},
      {q: "I ___ my teeth this morning.", o: ["brushed", "brush", "brushes"], c: 0},
      {q: "She ___ her bag.", o: ["found", "find", "finds"], c: 0},
      {q: "They ___ for three hours.", o: ["walked", "walk", "walks"], c: 0},
      {q: "He ___ music all day.", o: ["listened", "listen", "listens"], c: 0},
      {q: "You ___ everything.", o: ["understood", "understand", "understands"], c: 0}
    ]
  },

  // ========== A2 (15 TEMAS) ==========
  {
    level: 'A2',
    id: 19,
    title: 'Pasado simple de verbos irregulares',
    description: 'Verbos que no siguen patrón -ed. went, saw, had, ate, etc.',
    questions: [
      {q: "I ___ to the store yesterday.", o: ["went", "go", "goes"], c: 0},
      {q: "She ___ her phone at home.", o: ["forgot", "forget", "forgets"], c: 0},
      {q: "They ___ pizza for dinner.", o: ["ate", "eat", "eats"], c: 0},
      {q: "He ___ a book.", o: ["read", "reads", "reading"], c: 0},
      {q: "We ___ to the movies.", o: ["went", "go", "goes"], c: 0},
      {q: "I ___ him at the party.", o: ["saw", "see", "sees"], c: 0},
      {q: "She ___ a beautiful dress.", o: ["wore", "wear", "wears"], c: 0},
      {q: "They ___ to Paris.", o: ["flew", "fly", "flies"], c: 0},
      {q: "He ___ a cup of coffee.", o: ["drank", "drink", "drinks"], c: 0},
      {q: "I ___ my homework.", o: ["did", "do", "does"], c: 0},
      {q: "She ___ a new job.", o: ["got", "get", "gets"], c: 0},
      {q: "We ___ in the pool.", o: ["swam", "swim", "swims"], c: 0},
      {q: "They ___ early.", o: ["woke", "wake", "wakes"], c: 0},
      {q: "He ___ the car.", o: ["drove", "drive", "drives"], c: 0},
      {q: "I ___ a mistake.", o: ["made", "make", "makes"], c: 0},
      {q: "She ___ in the rain.", o: ["fell", "fall", "falls"], c: 0},
      {q: "They ___ the truth.", o: ["knew", "know", "knows"], c: 0},
      {q: "He ___ the window.", o: ["broke", "break", "breaks"], c: 0},
      {q: "I ___ my keys.", o: ["lost", "lose", "loses"], c: 0},
      {q: "She ___ the song.", o: ["sang", "sing", "sings"], c: 0}
    ]
  },
  {
    level: 'A2',
    id: 20,
    title: 'Futuro con "going to"',
    description: 'Planes e intenciones. am/is/are + going to + verbo base.',
    questions: [
      {q: "I am ___ to the beach tomorrow.", o: ["going", "go", "goes"], c: 0},
      {q: "She is ___ to study tonight.", o: ["going", "go", "goes"], c: 0},
      {q: "They are ___ to watch a movie.", o: ["going", "go", "goes"], c: 0},
      {q: "He is ___ to cook dinner.", o: ["going", "go", "goes"], c: 0},
      {q: "We are ___ to travel next month.", o: ["going", "go", "goes"], c: 0},
      {q: "I am ___ to call you later.", o: ["going", "go", "goes"], c: 0},
      {q: "She is ___ to buy a new car.", o: ["going", "go", "goes"], c: 0},
      {q: "They are ___ to have a party.", o: ["going", "go", "goes"], c: 0},
      {q: "You are ___ to love this movie.", o: ["going", "go", "goes"], c: 0},
      {q: "He is ___ to visit us.", o: ["going", "go", "goes"], c: 0},
      {q: "It is ___ to rain tomorrow.", o: ["going", "go", "goes"], c: 0},
      {q: "We are ___ to start the project.", o: ["going", "go", "goes"], c: 0},
      {q: "I am ___ to apply for that job.", o: ["going", "go", "goes"], c: 0},
      {q: "She is ___ to move to a new house.", o: ["going", "go", "goes"], c: 0},
      {q: "They are ___ to learn Spanish.", o: ["going", "go", "goes"], c: 0},
      {q: "He is ___ to propose to her.", o: ["going", "go", "goes"], c: 0},
      {q: "You are ___ to finish this project.", o: ["going", "go", "goes"], c: 0},
      {q: "We are ___ to fix the roof.", o: ["going", "go", "goes"], c: 0},
      {q: "I am ___ to take a vacation.", o: ["going", "go", "goes"], c: 0},
      {q: "She is ___ to open a restaurant.", o: ["going", "go", "goes"], c: 0}
    ]
  },
  {
    level: 'A2',
    id: 21,
    title: 'Futuro con "will"',
    description: 'Predicciones y decisiones espontáneas. will + verbo base.',
    questions: [
      {q: "I ___ help you tomorrow.", o: ["will", "am going to", "shall"], c: 0},
      {q: "She ___ finish the project.", o: ["will", "is going to", "shall"], c: 0},
      {q: "They ___ pass the exam.", o: ["will", "are going to", "shall"], c: 0},
      {q: "He ___ never forget this.", o: ["will", "is going to", "shall"], c: 0},
      {q: "We ___ probably arrive late.", o: ["will", "are going to", "shall"], c: 0},
      {q: "You ___ love this place.", o: ["will", "are going to", "shall"], c: 0},
      {q: "It ___ be sunny tomorrow.", o: ["will", "is going to", "shall"], c: 0},
      {q: "I ___ not forget.", o: ["will", "am going to", "shall"], c: 0},
      {q: "She ___ definitely be there.", o: ["will", "is going to", "shall"], c: 0},
      {q: "They ___ call you back.", o: ["will", "are going to", "shall"], c: 0},
      {q: "He ___ succeed in life.", o: ["will", "is going to", "shall"], c: 0},
      {q: "We ___ be happy together.", o: ["will", "are going to", "shall"], c: 0},
      {q: "I ___ support you always.", o: ["will", "am going to", "shall"], c: 0},
      {q: "She ___ become a doctor.", o: ["will", "is going to", "shall"], c: 0},
      {q: "They ___ win the competition.", o: ["will", "are going to", "shall"], c: 0},
      {q: "You ___ regret this decision.", o: ["will", "are going to", "shall"], c: 0},
      {q: "It ___ not happen again.", o: ["will", "is going to", "shall"], c: 0},
      {q: "We ___ solve this problem.", o: ["will", "are going to", "shall"], c: 0},
      {q: "I ___ write you a letter.", o: ["will", "am going to", "shall"], c: 0},
      {q: "She ___ probably agree with us.", o: ["will", "is going to", "shall"], c: 0}
    ]
  },
  {
    level: 'A2',
    id: 22,
    title: 'Comparativos y superlativos',
    description: 'bigger, biggest, more interesting, most interesting.',
    questions: [
      {q: "She is ___ than her sister.", o: ["taller", "tallest", "more tall"], c: 0},
      {q: "This book is ___ than that one.", o: ["more interesting", "interestinger", "most interesting"], c: 0},
      {q: "He is the ___ person I know.", o: ["smartest", "smarter", "most smart"], c: 0},
      {q: "The blue car is ___ the red one.", o: ["faster than", "the fastest", "fastest"], c: 0},
      {q: "This is the ___ restaurant in town.", o: ["best", "better", "good"], c: 0},
      {q: "She is ___ now.", o: ["happier", "happiness", "more happy"], c: 0},
      {q: "The weather today is ___ yesterday.", o: ["colder than", "the coldest", "more cold than"], c: 0},
      {q: "This is the ___ movie ever.", o: ["worst", "worse", "bad"], c: 0},
      {q: "He is ___ his brother.", o: ["younger than", "the youngest", "young than"], c: 0},
      {q: "The Pacific is the ___ ocean.", o: ["largest", "larger", "more large"], c: 0},
      {q: "She works ___ than me.", o: ["harder", "hardest", "more hard"], c: 0},
      {q: "This problem is ___ than I thought.", o: ["more complicated", "complicateder", "most complicated"], c: 0},
      {q: "The elephant is ___ the mouse.", o: ["bigger than", "the biggest", "more big than"], c: 0},
      {q: "He is the ___ student in class.", o: ["best", "better", "good"], c: 0},
      {q: "This job is ___ my previous one.", o: ["better than", "the best", "more good than"], c: 0},
      {q: "She is ___ now.", o: ["more confident", "confidenter", "most confident"], c: 0},
      {q: "This is the ___ day of my life.", o: ["best", "better", "good"], c: 0},
      {q: "The mountain is ___ the hill.", o: ["higher than", "the highest", "more high than"], c: 0},
      {q: "He is the ___ person in the group.", o: ["laziest", "lazier", "most lazy"], c: 0},
      {q: "This product is ___ quality.", o: ["higher", "highest", "more high"], c: 0}
    ]
  },
  {
    level: 'A2',
    id: 23,
    title: 'Adverbios de modo',
    description: 'slowly, quickly, carefully, well, badly. Modifican verbos.',
    questions: [
      {q: "She speaks English ___.", o: ["fluently", "fluent", "fluence"], c: 0},
      {q: "He drives ___.", o: ["carefully", "careful", "with care"], c: 0},
      {q: "They run ___.", o: ["quickly", "quick", "speed"], c: 0},
      {q: "She sings ___.", o: ["beautifully", "beautiful", "beauty"], c: 0},
      {q: "He works ___.", o: ["efficiently", "efficient", "effect"], c: 0},
      {q: "They move ___.", o: ["slowly", "slow", "slowness"], c: 0},
      {q: "She answered the question ___.", o: ["correctly", "correct", "correctly"], c: 0},
      {q: "He behaved ___.", o: ["badly", "bad", "badness"], c: 0},
      {q: "They completed the task ___.", o: ["successfully", "successful", "success"], c: 0},
      {q: "She handled the situation ___.", o: ["wisely", "wise", "wisdom"], c: 0},
      {q: "He performs ___.", o: ["excellently", "excellent", "excellence"], c: 0},
      {q: "They communicate ___.", o: ["clearly", "clear", "clarity"], c: 0},
      {q: "She solves problems ___.", o: ["logically", "logical", "logic"], c: 0},
      {q: "He listened ___.", o: ["attentively", "attentive", "attention"], c: 0},
      {q: "They greeted us ___.", o: ["warmly", "warm", "warmth"], c: 0},
      {q: "She danced ___.", o: ["gracefully", "graceful", "grace"], c: 0},
      {q: "He explained ___.", o: ["clearly", "clear", "clarity"], c: 0},
      {q: "They organized ___.", o: ["neatly", "neat", "neatness"], c: 0},
      {q: "She worked ___.", o: ["diligently", "diligent", "diligence"], c: 0},
      {q: "He treated us ___.", o: ["kindly", "kind", "kindness"], c: 0}
    ]
  },
  {
    level: 'A2',
    id: 24,
    title: 'Pronombres objeto',
    description: 'me, you, him, her, it, us, them. Objeto directo del verbo.',
    questions: [
      {q: "I love ___.", o: ["you", "your", "yours"], c: 0},
      {q: "She sees ___.", o: ["him", "his", "he"], c: 0},
      {q: "They invite ___.", o: ["me", "my", "I"], c: 0},
      {q: "He knows ___.", o: ["her", "hers", "she"], c: 0},
      {q: "We like ___.", o: ["them", "their", "they"], c: 0},
      {q: "You help ___.", o: ["us", "our", "we"], c: 0},
      {q: "She gives a gift to ___.", o: ["him", "his", "he"], c: 0},
      {q: "I call ___.", o: ["you", "your", "yours"], c: 0},
      {q: "They tell ___ the truth.", o: ["us", "our", "we"], c: 0},
      {q: "He teaches ___.", o: ["them", "their", "they"], c: 0},
      {q: "She hugs ___.", o: ["me", "my", "I"], c: 0},
      {q: "We invite ___.", o: ["her", "hers", "she"], c: 0},
      {q: "You know ___.", o: ["it", "its", "it's"], c: 0},
      {q: "They visit ___.", o: ["us", "our", "we"], c: 0},
      {q: "I love ___.", o: ["them", "their", "they"], c: 0},
      {q: "She asks ___ for help.", o: ["him", "his", "he"], c: 0},
      {q: "He watches ___.", o: ["you", "your", "yours"], c: 0},
      {q: "We understand ___.", o: ["her", "hers", "she"], c: 0},
      {q: "They respect ___.", o: ["me", "my", "I"], c: 0},
      {q: "I trust ___.", o: ["you", "your", "yours"], c: 0}
    ]
  },
  {
    level: 'A2',
    id: 25,
    title: 'Sustantivos contables e incontables',
    description: 'Countable: a book, books. Uncountable: water, music, information.',
    questions: [
      {q: "There is ___ water in the glass.", o: ["some", "a", "an"], c: 0},
      {q: "I have ___ apples.", o: ["several", "some water", "milk"], c: 0},
      {q: "Can I have ___ sugar, please?", o: ["some", "a", "an"], c: 0},
      {q: "There are ___ students in class.", o: ["many", "much", "a lot of water"], c: 0},
      {q: "She doesn't have ___ money.", o: ["much", "many", "several"], c: 0},
      {q: "How ___ books do you have?", o: ["many", "much", "a lot of"], c: 0},
      {q: "I don't have ___ time.", o: ["much", "many", "several"], c: 0},
      {q: "There are ___ chairs in the room.", o: ["several", "much", "a lot of water"], c: 0},
      {q: "Do you want ___ coffee?", o: ["some", "a", "several"], c: 0},
      {q: "She has ___ books.", o: ["many", "much", "a lot of water"], c: 0},
      {q: "There is not ___ salt in the soup.", o: ["enough", "enough", "many"], c: 0},
      {q: "He drinks ___ tea every day.", o: ["a lot of", "many", "several"], c: 0},
      {q: "How ___ luggage do you have?", o: ["much", "many", "several"], c: 0},
      {q: "I need ___ information about the project.", o: ["some", "a", "several"], c: 0},
      {q: "There are not ___ cars on the street.", o: ["many", "much", "a lot of water"], c: 0},
      {q: "She needs ___ help with this task.", o: ["some", "a", "several"], c: 0},
      {q: "How ___ eggs are there?", o: ["many", "much", "a lot of"], c: 0},
      {q: "I don't have ___ experience.", o: ["much", "many", "several"], c: 0},
      {q: "There is ___ furniture in the house.", o: ["some", "a lot of", "many"], c: 1},
      {q: "He spent ___ money on vacation.", o: ["a lot of", "many", "several"], c: 0}
    ]
  },
  {
    level: 'A2',
    id: 26,
    title: 'Presente perfecto',
    description: 'Acción sin especificar cuándo. have/has + participio pasado.',
    questions: [
      {q: "I ___ been to Paris.", o: ["have", "has", "am"], c: 0},
      {q: "She ___ finished her work.", o: ["has", "have", "is"], c: 0},
      {q: "They ___ lived here for years.", o: ["have", "has", "are"], c: 0},
      {q: "He ___ never seen a rainbow.", o: ["has", "have", "is"], c: 0},
      {q: "We ___ just arrived.", o: ["have", "has", "are"], c: 0},
      {q: "You ___ already eaten.", o: ["have", "has", "are"], c: 0},
      {q: "I ___ worked here for three years.", o: ["have", "has", "am"], c: 0},
      {q: "She ___ lost her phone.", o: ["has", "have", "is"], c: 0},
      {q: "They ___ not finished yet.", o: ["have", "has", "are"], c: 0},
      {q: "He ___ been sick.", o: ["has", "have", "is"], c: 0},
      {q: "We ___ visited ten countries.", o: ["have", "has", "are"], c: 0},
      {q: "I ___ known her for a long time.", o: ["have", "has", "am"], c: 0},
      {q: "She ___ changed her mind.", o: ["has", "have", "is"], c: 0},
      {q: "They ___ played together since childhood.", o: ["have", "has", "are"], c: 0},
      {q: "He ___ broken his arm.", o: ["has", "have", "is"], c: 0},
      {q: "You ___ done an excellent job.", o: ["have", "has", "are"], c: 0},
      {q: "We ___ never tried this restaurant.", o: ["have", "has", "are"], c: 0},
      {q: "I ___ made a mistake.", o: ["have", "has", "am"], c: 0},
      {q: "She ___ always wanted to travel.", o: ["has", "have", "is"], c: 0},
      {q: "They ___ won the championship.", o: ["have", "has", "are"], c: 0}
    ]
  },
  {
    level: 'A2',
    id: 27,
    title: 'Preposiciones de movimiento',
    description: 'into, out of, through, along, around, across, up, down.',
    questions: [
      {q: "The cat ran ___ the house.", o: ["into", "on", "at"], c: 0},
      {q: "They walked ___ the park.", o: ["through", "in", "at"], c: 0},
      {q: "She jumped ___ the pool.", o: ["into", "on", "at"], c: 0},
      {q: "He came ___ the room.", o: ["out of", "on", "at"], c: 0},
      {q: "We drove ___ the bridge.", o: ["across", "on", "at"], c: 0},
      {q: "The river flows ___ the valley.", o: ["through", "in", "at"], c: 0},
      {q: "They walked ___ the beach.", o: ["along", "on", "at"], c: 0},
      {q: "The plane flew ___ the clouds.", o: ["through", "in", "at"], c: 0},
      {q: "She ran ___ the stairs.", o: ["up", "on", "at"], c: 0},
      {q: "He walked ___ the street.", o: ["down", "in", "on"], c: 1},
      {q: "The horse galloped ___ the field.", o: ["around", "on", "at"], c: 0},
      {q: "We swam ___ the sea.", o: ["across", "in", "on"], c: 0},
      {q: "She climbed ___ the mountain.", o: ["up", "on", "at"], c: 0},
      {q: "They escaped ___ the prison.", o: ["out of", "on", "at"], c: 0},
      {q: "The train went ___ the tunnel.", o: ["through", "in", "at"], c: 0},
      {q: "He slid ___ the slide.", o: ["down", "on", "at"], c: 0},
      {q: "She walked ___ the house and ___.", o: ["around the", "through the", "across the"], c: 1},
      {q: "We moved ___ the sofa.", o: ["around", "on", "at"], c: 0},
      {q: "The road goes ___ the mountains.", o: ["through", "in", "at"], c: 0},
      {q: "They ran ___ the field.", o: ["across", "on", "at"], c: 0}
    ]
  },
  {
    level: 'A2',
    id: 28,
    title: 'Condicionales tipo 0 y 1',
    description: 'Type 0: If you heat water, it boils. Type 1: If it rains, I will stay home.',
    questions: [
      {q: "If you ___ ice, it melts.", o: ["heat", "heated", "will heat"], c: 0},
      {q: "If it rains, I ___ home.", o: ["will stay", "stay", "staying"], c: 0},
      {q: "If she ___ hard, she will pass.", o: ["studies", "study", "will study"], c: 0},
      {q: "If you ___ the button, the light comes on.", o: ["press", "pressed", "will press"], c: 0},
      {q: "If he ___, he will miss the bus.", o: ["is late", "was late", "will be late"], c: 0},
      {q: "If plants don't have water, they ___.", o: ["die", "died", "will die"], c: 0},
      {q: "If we ___ now, we will arrive on time.", o: ["leave", "left", "will leave"], c: 0},
      {q: "If people ___ vegetables, they are healthier.", o: ["eat", "ate", "will eat"], c: 0},
      {q: "If you ___ the recipe, the dish will taste good.", o: ["follow", "followed", "will follow"], c: 0},
      {q: "If the temperature ___ zero, water freezes.", o: ["is", "was", "will be"], c: 0},
      {q: "If I ___ time, I will call you.", o: ["have", "had", "will have"], c: 0},
      {q: "If she ___ her homework, she can play.", o: ["finishes", "finished", "will finish"], c: 0},
      {q: "If it's sunny tomorrow, we ___ to the beach.", o: ["will go", "go", "going"], c: 0},
      {q: "If you ___ salt to water, it boils faster.", o: ["add", "added", "will add"], c: 0},
      {q: "If they ___ early, they will get good seats.", o: ["arrive", "arrived", "will arrive"], c: 0},
      {q: "If you mix red and blue, you ___ purple.", o: ["get", "got", "will get"], c: 0},
      {q: "If I ___ you, I will be happy.", o: ["see", "saw", "will see"], c: 0},
      {q: "If birds ___ wings, they can fly.", o: ["have", "had", "will have"], c: 0},
      {q: "If he ___ a lot, he will be tired.", o: ["runs", "ran", "will run"], c: 0},
      {q: "If you ___ to bed late, you will be tired.", o: ["go", "went", "will go"], c: 0}
    ]
  },
  {
    level: 'A2',
    id: 29,
    title: 'Modales de obligación y recomendación',
    description: 'must, have to, should, ought to. Obligación y consejo.',
    questions: [
      {q: "You ___ wear a seatbelt when driving.", o: ["must", "should", "might"], c: 0},
      {q: "Students ___ do their homework.", o: ["have to", "might", "could"], c: 0},
      {q: "You ___ see a doctor if you are sick.", o: ["should", "could", "might"], c: 0},
      {q: "Everyone ___ follow the rules.", o: ["must", "might", "could"], c: 0},
      {q: "You ___ be on time for the meeting.", o: ["have to", "might", "could"], c: 0},
      {q: "I ___ tell you something important.", o: ["have to", "might", "could"], c: 0},
      {q: "She ___ eat more vegetables.", o: ["should", "might", "could"], c: 0},
      {q: "You ___ pay the bill by Friday.", o: ["must", "might", "could"], c: 0},
      {q: "He ___ take this medicine.", o: ["has to", "might", "could"], c: 0},
      {q: "You ___ worry about it.", o: ["shouldn't", "must", "have to"], c: 0},
      {q: "Workers ___ wear safety equipment.", o: ["must", "might", "could"], c: 0},
      {q: "I ___ leave now.", o: ["have to", "might", "could"], c: 0},
      {q: "You ___ listen to advice.", o: ["should", "might", "must"], c: 0},
      {q: "Children ___ obey their parents.", o: ["must", "might", "could"], c: 0},
      {q: "You ___ drink more water.", o: ["should", "might", "must"], c: 0},
      {q: "She ___ finish the project today.", o: ["has to", "might", "could"], c: 0},
      {q: "You ___ call your mother.", o: ["should", "might", "must"], c: 0},
      {q: "It ___ be done immediately.", o: ["must", "might", "could"], c: 0},
      {q: "You ___ try this restaurant.", o: ["should", "might", "must"], c: 0},
      {q: "He ___ take a vacation soon.", o: ["should", "might", "must"], c: 0}
    ]
  },
  {
    level: 'A2',
    id: 30,
    title: 'Question tags',
    description: 'You are English, aren\'t you? He doesn\'t like coffee, does he?',
    questions: [
      {q: "You speak English, ___ ?", o: ["don't you", "do you", "you do"], c: 0},
      {q: "She doesn't like coffee, ___ ?", o: ["does she", "doesn't she", "she does"], c: 0},
      {q: "They are students, ___ ?", o: ["aren't they", "are they", "they are"], c: 0},
      {q: "He doesn't work here, ___ ?", o: ["does he", "doesn't he", "he does"], c: 0},
      {q: "We are friends, ___ ?", o: ["aren't we", "are we", "we are"], c: 0},
      {q: "You didn't see the movie, ___ ?", o: ["did you", "didn't you", "you did"], c: 0},
      {q: "She has been there, ___ ?", o: ["hasn't she", "has she", "she has"], c: 0},
      {q: "They will come tomorrow, ___ ?", o: ["won't they", "will they", "they will"], c: 0},
      {q: "He can swim, ___ ?", o: ["can't he", "can he", "he can"], c: 0},
      {q: "I am late, ___ ?", o: ["aren't I", "am I", "I am"], c: 0},
      {q: "You like pizza, ___ ?", o: ["don't you", "do you", "you do"], c: 0},
      {q: "She has finished, ___ ?", o: ["hasn't she", "has she", "she has"], c: 0},
      {q: "They don't know, ___ ?", o: ["do they", "don't they", "they don't"], c: 0},
      {q: "He was sick, ___ ?", o: ["wasn't he", "was he", "he was"], c: 0},
      {q: "We should leave, ___ ?", o: ["shouldn't we", "should we", "we should"], c: 0},
      {q: "I can help, ___ ?", o: ["can't I", "can I", "I can"], c: 0},
      {q: "You haven't eaten, ___ ?", o: ["have you", "haven't you", "you have"], c: 0},
      {q: "She will agree, ___ ?", o: ["won't she", "will she", "she will"], c: 0},
      {q: "They could come, ___ ?", o: ["couldn't they", "could they", "they could"], c: 0},
      {q: "He doesn't mind, ___ ?", o: ["does he", "doesn't he", "he does"], c: 0}
    ]
  },
  {
    level: 'A2',
    id: 31,
    title: 'Used to',
    description: 'Acciones habituales en el pasado. I used to play football.',
    questions: [
      {q: "I ___ play football when I was young.", o: ["used to", "use to", "am used to"], c: 0},
      {q: "She ___ live in a small town.", o: ["used to", "use to", "is used to"], c: 0},
      {q: "They ___ visit us every summer.", o: ["used to", "use to", "are used to"], c: 0},
      {q: "He ___ smoke, but he quit.", o: ["used to", "use to", "is used to"], c: 0},
      {q: "We ___ go camping every year.", o: ["used to", "use to", "are used to"], c: 0},
      {q: "I ___ wake up early.", o: ["used to", "use to", "am used to"], c: 0},
      {q: "She ___ work at a bank.", o: ["used to", "use to", "is used to"], c: 0},
      {q: "They ___ eat meat, but now they're vegetarian.", o: ["used to", "use to", "are used to"], c: 0},
      {q: "He ___ wear glasses.", o: ["used to", "use to", "is used to"], c: 0},
      {q: "We ___ know each other.", o: ["used to", "use to", "are used to"], c: 0},
      {q: "I ___ ride a bike to school.", o: ["used to", "use to", "am used to"], c: 0},
      {q: "She ___ be very shy.", o: ["used to", "use to", "is used to"], c: 0},
      {q: "They ___ have a dog.", o: ["used to", "use to", "are used to"], c: 0},
      {q: "He ___ drink coffee every morning.", o: ["used to", "use to", "is used to"], c: 0},
      {q: "We ___ take vacations in Spain.", o: ["used to", "use to", "are used to"], c: 0},
      {q: "I ___ believe in Santa Claus.", o: ["used to", "use to", "am used to"], c: 0},
      {q: "She ___ teach English.", o: ["used to", "use to", "is used to"], c: 0},
      {q: "They ___ fight a lot.", o: ["used to", "use to", "are used to"], c: 0},
      {q: "He ___ play the piano.", o: ["used to", "use to", "is used to"], c: 0},
      {q: "I ___ be afraid of the dark.", o: ["used to", "use to", "am used to"], c: 0}
    ]
  },
  {
    level: 'A2',
    id: 32,
    title: 'Pronombres reflexivos',
    description: 'myself, yourself, himself, herself, itself, ourselves, themselves.',
    questions: [
      {q: "I can do it ___.", o: ["myself", "me", "I"], c: 0},
      {q: "She talks to ___.", o: ["herself", "her", "she"], c: 0},
      {q: "They enjoy ___.", o: ["themselves", "them", "they"], c: 0},
      {q: "He hurt ___.", o: ["himself", "him", "he"], c: 0},
      {q: "We can solve it ___.", o: ["ourselves", "us", "we"], c: 0},
      {q: "You should be proud of ___.", o: ["yourself", "you", "your"], c: 0},
      {q: "The cat cleaned ___.", o: ["itself", "it", "its"], c: 0},
      {q: "I prepare ___ for the exam.", o: ["myself", "me", "I"], c: 0},
      {q: "She bought ___ a new dress.", o: ["herself", "her", "she"], c: 0},
      {q: "They protected ___ from danger.", o: ["themselves", "them", "they"], c: 0},
      {q: "He annoyed ___ with his mistake.", o: ["himself", "him", "he"], c: 0},
      {q: "We must defend ___.", o: ["ourselves", "us", "we"], c: 0},
      {q: "Do you ever talk to ___?", o: ["yourself", "you", "your"], c: 0},
      {q: "The dog licked ___.", o: ["itself", "it", "its"], c: 0},
      {q: "I saw ___ in the mirror.", o: ["myself", "me", "I"], c: 0},
      {q: "She locked ___ in the room.", o: ["herself", "her", "she"], c: 0},
      {q: "They hurt ___ during the accident.", o: ["themselves", "them", "they"], c: 0},
      {q: "He introduced ___.", o: ["himself", "him", "he"], c: 0},
      {q: "We were proud of ___.", o: ["ourselves", "us", "we"], c: 0},
      {q: "You can do it ___.", o: ["yourself", "you", "your"], c: 0}
    ]
  },
  {
    level: 'A2',
    id: 33,
    title: 'Pasado continuo',
    description: 'Acción en progreso en el pasado. was/were + -ing.',
    questions: [
      {q: "I ___ TV when you called.", o: ["was watching", "watched", "was watch"], c: 0},
      {q: "She ___ a book all day.", o: ["was reading", "read", "was read"], c: 0},
      {q: "They ___ football when it started to rain.", o: ["were playing", "played", "were play"], c: 0},
      {q: "He ___ dinner when she arrived.", o: ["was cooking", "cooked", "was cook"], c: 0},
      {q: "We ___ at 10 p.m.", o: ["were sleeping", "slept", "were sleep"], c: 0},
      {q: "You ___ very loudly.", o: ["were talking", "talked", "were talk"], c: 0},
      {q: "I ___ when the phone rang.", o: ["was sleeping", "slept", "was sleep"], c: 0},
      {q: "She ___ in the garden.", o: ["was working", "worked", "was work"], c: 0},
      {q: "They ___ at the party.", o: ["were dancing", "danced", "were dance"], c: 0},
      {q: "He ___ his homework.", o: ["was doing", "did", "was do"], c: 0},
      {q: "We ___ for the bus.", o: ["were waiting", "waited", "were wait"], c: 0},
      {q: "I ___ to my friend.", o: ["was talking", "talked", "was talk"], c: 0},
      {q: "She ___ her makeup.", o: ["was applying", "applied", "was apply"], c: 0},
      {q: "They ___ a movie.", o: ["were watching", "watched", "were watch"], c: 0},
      {q: "He ___ the car.", o: ["was washing", "washed", "was wash"], c: 0},
      {q: "You ___ very carefully.", o: ["were listening", "listened", "were listen"], c: 0},
      {q: "I ___ about you.", o: ["was thinking", "thought", "was think"], c: 0},
      {q: "She ___ the house.", o: ["was cleaning", "cleaned", "was clean"], c: 0},
      {q: "They ___ in the pool.", o: ["were swimming", "swam", "were swim"], c: 0},
      {q: "He ___ music.", o: ["was playing", "played", "was play"], c: 0}
    ]
  },

  // ========== B1 (15 TEMAS) ==========
  // [Continuaremos con B1, B2, C1...]
  // Por brevedad, aquí solo muestro la estructura. En producción, cada tema tendría 20 preguntas.
  {
    level: 'B1',
    id: 34,
    title: 'Presente perfecto continuo',
    description: 'Acción que comenzó en el pasado y continúa. have/has been + -ing.',
    questions: [
      {q: "I ___ English for 5 years.", o: ["have been studying", "have studied", "study"], c: 0},
      {q: "She ___ in the garden all morning.", o: ["has been working", "has worked", "works"], c: 0},
      {q: "They ___ for two hours.", o: ["have been waiting", "have waited", "wait"], c: 0},
      {q: "He ___ since 6 a.m.", o: ["has been working", "has worked", "works"], c: 0},
      {q: "We ___ this project for months.", o: ["have been doing", "have done", "do"], c: 0},
      {q: "I ___ on this problem all day.", o: ["have been working", "have worked", "work"], c: 0},
      {q: "She ___ here since 2020.", o: ["has been living", "has lived", "lives"], c: 0},
      {q: "They ___ for the same company for years.", o: ["have been working", "have worked", "work"], c: 0},
      {q: "He ___ to reach you.", o: ["has been trying", "has tried", "tries"], c: 0},
      {q: "We ___ about the issue.", o: ["have been discussing", "have discussed", "discuss"], c: 0},
      {q: "I ___ lately.", o: ["have been feeling", "have felt", "feel"], c: 0},
      {q: "She ___ with the problem for hours.", o: ["has been struggling", "has struggled", "struggles"], c: 0},
      {q: "They ___ me repeatedly.", o: ["have been asking", "have asked", "ask"], c: 0},
      {q: "He ___ on the project since yesterday.", o: ["has been working", "has worked", "works"], c: 0},
      {q: "We ___ here since childhood.", o: ["have been living", "have lived", "live"], c: 0},
      {q: "I ___ this book for a week.", o: ["have been reading", "have read", "read"], c: 0},
      {q: "She ___ all afternoon.", o: ["has been cooking", "has cooked", "cooks"], c: 0},
      {q: "They ___ about the plan.", o: ["have been talking", "have talked", "talk"], c: 0},
      {q: "He ___ his old habits.", o: ["has been avoiding", "has avoided", "avoids"], c: 0},
      {q: "You ___ me all day.", o: ["have been ignoring", "have ignored", "ignore"], c: 0}
    ]
  },
  {
    level: 'B1',
    id: 35,
    title: 'Pasado perfecto simple',
    description: 'Acción anterior a otra en el pasado. had + participio pasado.',
    questions: [
      {q: "She ___ left before I arrived.", o: ["had", "has", "was"], c: 0},
      {q: "They ___ finished the work.", o: ["had", "have", "were"], c: 0},
      {q: "I ___ never seen anything like it.", o: ["had", "have", "was"], c: 0},
      {q: "He ___ already gone.", o: ["had", "has", "was"], c: 0},
      {q: "We ___ just arrived when you called.", o: ["had", "have", "were"], c: 0},
      {q: "By the time we got there, they ___ left.", o: ["had", "have", "were"], c: 0},
      {q: "She ___ never traveled before.", o: ["had", "has", "was"], c: 0},
      {q: "They ___ not told anyone about it.", o: ["had", "have", "were"], c: 0},
      {q: "I ___ been there before.", o: ["had", "have", "was"], c: 0},
      {q: "He ___ already eaten dinner.", o: ["had", "has", "was"], c: 0},
      {q: "We ___ planned everything carefully.", o: ["had", "have", "were"], c: 0},
      {q: "The train ___ left by the time we got to the station.", o: ["had", "has", "was"], c: 0},
      {q: "She ___ learned Spanish before moving to Spain.", o: ["had", "has", "was"], c: 0},
      {q: "They ___ already seen the movie.", o: ["had", "have", "were"], c: 0},
      {q: "I ___ forgotten my keys at home.", o: ["had", "have", "was"], c: 0},
      {q: "By midnight, everyone ___ gone to bed.", o: ["had", "have", "was"], c: 0},
      {q: "She ___ worked there for ten years before retiring.", o: ["had", "has", "was"], c: 0},
      {q: "They ___ not expected such difficulty.", o: ["had", "have", "were"], c: 0},
      {q: "He ___ suffered a lot.", o: ["had", "has", "was"], c: 0},
      {q: "We ___ understood the instructions.", o: ["had", "have", "were"], c: 0}
    ]
  },
  {
    level: 'B1',
    id: 36,
    title: 'Voz pasiva — tiempos básicos',
    description: 'The house was built in 1990. The letter is being written.',
    questions: [
      {q: "The book ___ by Shakespeare.", o: ["was written", "wrote", "written"], c: 0},
      {q: "The house ___ last year.", o: ["was built", "built", "building"], c: 0},
      {q: "The letter ___ by the secretary.", o: ["is typed", "types", "typing"], c: 0},
      {q: "The car ___ in Japan.", o: ["is made", "makes", "making"], c: 0},
      {q: "The project ___ next week.", o: ["will be finished", "finishes", "finishing"], c: 0},
      {q: "The dinner ___ by the chef.", o: ["is prepared", "prepares", "preparing"], c: 0},
      {q: "The cake ___ by my mother.", o: ["was baked", "baked", "baking"], c: 0},
      {q: "The trees ___ during the storm.", o: ["were damaged", "damaged", "damaging"], c: 0},
      {q: "The report ___ tomorrow.", o: ["will be submitted", "submits", "submitting"], c: 0},
      {q: "The problem ___ by the team.", o: ["was solved", "solved", "solving"], c: 0},
      {q: "The windows ___ right now.", o: ["are being cleaned", "clean", "cleaning"], c: 0},
      {q: "The song ___ by millions.", o: ["is sung", "sings", "singing"], c: 0},
      {q: "The city ___ in the 15th century.", o: ["was founded", "founded", "founding"], c: 0},
      {q: "The picture ___ on the wall.", o: ["is hung", "hangs", "hanging"], c: 0},
      {q: "The announcement ___ yesterday.", o: ["was made", "made", "making"], c: 0},
      {q: "The exam ___ next Monday.", o: ["will be held", "holds", "holding"], c: 0},
      {q: "The emails ___ by the system.", o: ["are sent", "send", "sending"], c: 0},
      {q: "The bridge ___ by engineers.", o: ["was designed", "designed", "designing"], c: 0},
      {q: "The meeting ___ at 3 p.m.", o: ["will be held", "holds", "holding"], c: 0},
      {q: "The mistake ___ immediately.", o: ["was corrected", "corrected", "correcting"], c: 0}
    ]
  },
  {
    level: 'B1',
    id: 37,
    title: 'Condicional tipo 2',
    description: 'Situación hipotética en presente. If I had money, I would travel.',
    questions: [
      {q: "If I ___ money, I would travel.", o: ["had", "have", "would have"], c: 0},
      {q: "If she ___ here, she would help us.", o: ["was", "is", "would be"], c: 0},
      {q: "If they ___ the truth, things would be different.", o: ["knew", "know", "would know"], c: 0},
      {q: "If he ___ faster, he would catch the bus.", o: ["ran", "runs", "would run"], c: 0},
      {q: "If we ___ in London, we would visit the museums.", o: ["lived", "live", "would live"], c: 0},
      {q: "If I ___ the answer, I would tell you.", o: ["knew", "know", "would know"], c: 0},
      {q: "If she ___ free time, she would read more.", o: ["had", "has", "would have"], c: 0},
      {q: "If they ___ rich, they would buy a big house.", o: ["were", "are", "would be"], c: 0},
      {q: "If you ___ here, you would understand.", o: ["were", "are", "would be"], c: 0},
      {q: "If I ___ younger, I would go skydiving.", o: ["was", "am", "would be"], c: 0},
      {q: "If she ___ brave enough, she would do it.", o: ["was", "is", "would be"], c: 0},
      {q: "If they ___ the rules, they wouldn't get in trouble.", o: ["followed", "follow", "would follow"], c: 0},
      {q: "If he ___ more time, he would finish it.", o: ["had", "has", "would have"], c: 0},
      {q: "If I ___ to the party, I would see you.", o: ["went", "go", "would go"], c: 0},
      {q: "If she ___ able to fly, she would visit everywhere.", o: ["could", "can", "would can"], c: 0},
      {q: "If they ___ the truth about him, they'd be shocked.", o: ["knew", "know", "would know"], c: 0},
      {q: "If I ___ in your place, I would quit.", o: ["was", "am", "would be"], c: 0},
      {q: "If you ___ me, I would be grateful.", o: ["helped", "help", "would help"], c: 0},
      {q: "If she ___ at the meeting, she would hear the news.", o: ["was", "is", "would be"], c: 0},
      {q: "If they ___ early, they would finish by noon.", o: ["started", "start", "would start"], c: 0}
    ]
  },
  {
    level: 'B1',
    id: 38,
    title: 'Verbos modales del pasado',
    description: 'could have, should have, might have, must have.',
    questions: [
      {q: "She ___ done better if she had studied.", o: ["could have", "could", "can have"], c: 0},
      {q: "He ___ told us about it.", o: ["should have", "should", "shall have"], c: 0},
      {q: "They ___ been late because of traffic.", o: ["might have", "might", "may have"], c: 0},
      {q: "I ___ that mistake.", o: ["shouldn't have made", "shouldn't make", "haven't made"], c: 0},
      {q: "She ___ noticed the difference.", o: ["must have", "must", "has"], c: 0},
      {q: "He ___ helped us, but he didn't.", o: ["could have", "could", "can have"], c: 0},
      {q: "You ___ asked first.", o: ["should have", "should", "shall have"], c: 0},
      {q: "They ___ seen the accident.", o: ["must have", "must", "have"], c: 0},
      {q: "I ___ something wrong.", o: ["must have done", "must do", "have done"], c: 0},
      {q: "She ___ the train.", o: ["might have missed", "might miss", "has missed"], c: 0},
      {q: "He ___ the instructions more carefully.", o: ["should have read", "should read", "has read"], c: 0},
      {q: "They ___ forgotten about the appointment.", o: ["might have", "might", "may have"], c: 0},
      {q: "I ___ for help.", o: ["could have asked", "could ask", "have asked"], c: 0},
      {q: "She ___ the truth if she had known.", o: ["would have told", "would tell", "tells"], c: 0},
      {q: "He ___ there earlier.", o: ["could have arrived", "could arrive", "has arrived"], c: 0},
      {q: "You ___ that behavior.", o: ["shouldn't have tolerated", "shouldn't tolerate", "haven't tolerated"], c: 0},
      {q: "They ___ the problem sooner.", o: ["should have solved", "should solve", "have solved"], c: 0},
      {q: "I ___ in that situation.", o: ["wouldn't have found myself", "wouldn't find myself", "haven't found myself"], c: 0},
      {q: "She ___ anything about it.", o: ["couldn't have known", "couldn't know", "hasn't known"], c: 0},
      {q: "He ___ better.", o: ["could have done", "could do", "has done"], c: 0}
    ]
  },
  {
    level: 'B1',
    id: 39,
    title: 'Oraciones de relativo (defining)',
    description: 'The man who lives here. The book that I read. Información esencial.',
    questions: [
      {q: "The person ___ lives next door is very friendly.", o: ["who", "which", "where"], c: 0},
      {q: "The book ___ I bought is excellent.", o: ["that", "which", "where"], c: 0},
      {q: "The car ___ is parked here is mine.", o: ["that", "which", "who"], c: 0},
      {q: "The girl ___ name is Sarah is my friend.", o: ["whose", "who", "that"], c: 0},
      {q: "The restaurant ___ we ate was amazing.", o: ["where", "that", "which"], c: 0},
      {q: "The time ___ you arrived was perfect.", o: ["when", "that", "which"], c: 0},
      {q: "The reason ___ he left is unclear.", o: ["why", "that", "which"], c: 0},
      {q: "The house ___ has a big garden is expensive.", o: ["that", "which", "who"], c: 0},
      {q: "The students ___ passed the exam are happy.", o: ["who", "that", "which"], c: 0},
      {q: "The movie ___ we watched was boring.", o: ["that", "which", "where"], c: 0},
      {q: "The man ___ helped us was very kind.", o: ["who", "that", "which"], c: 0},
      {q: "The place ___ you grew up must be special.", o: ["where", "that", "which"], c: 0},
      {q: "The device ___ screen is broken is useless.", o: ["whose", "that", "which"], c: 0},
      {q: "The company ___ I work for is international.", o: ["that", "which", "where"], c: 0},
      {q: "The people ___ you met are scientists.", o: ["that", "who", "which"], c: 0},
      {q: "The day ___ he was born was rainy.", o: ["when", "that", "which"], c: 0},
      {q: "The method ___ works best is the simplest one.", o: ["that", "which", "who"], c: 0},
      {q: "The school ___ teaches languages is modern.", o: ["that", "which", "who"], c: 0},
      {q: "The artist ___ paintings I admire is famous.", o: ["whose", "that", "which"], c: 0},
      {q: "The way ___ he speaks is distinctive.", o: ["that", "which", "where"], c: 0}
    ]
  },
  {
    level: 'B1',
    id: 40,
    title: 'Verbos con gerundio e infinitivo',
    description: 'Love swimming. Try to find. Algunos verbos aceptan ambas formas.',
    questions: [
      {q: "I enjoy ___ music.", o: ["listening to", "listen to", "to listen to"], c: 0},
      {q: "She stopped ___ out.", o: ["going", "to go", "go"], c: 0},
      {q: "We started ___ English.", o: ["learning", "to learn", "learn"], c: 0},
      {q: "He refused ___ help.", o: ["to accept", "accepting", "accept"], c: 0},
      {q: "I love ___ by the sea.", o: ["walking", "to walk", "walk"], c: 0},
      {q: "She forgot ___ the keys.", o: ["to lock", "locking", "lock"], c: 0},
      {q: "We avoided ___ late.", o: ["being", "to be", "be"], c: 0},
      {q: "He finished ___ his homework.", o: ["doing", "to do", "do"], c: 0},
      {q: "I hope ___ you soon.", o: ["to see", "seeing", "see"], c: 0},
      {q: "She wants ___ abroad.", o: ["to travel", "traveling", "travel"], c: 0},
      {q: "We keep ___ about it.", o: ["forgetting", "to forget", "forget"], c: 0},
      {q: "He managed ___ the problem.", o: ["to solve", "solving", "solve"], c: 0},
      {q: "I can't stand ___ music.", o: ["listening to", "to listen to", "listen to"], c: 0},
      {q: "She decided ___ a doctor.", o: ["to become", "becoming", "become"], c: 0},
      {q: "We permit ___ smoking.", o: ["no", "not", "none"], c: 0},
      {q: "He pretended ___ sick.", o: ["to be", "being", "be"], c: 0},
      {q: "I suggest ___ early.", o: ["leaving", "to leave", "leave"], c: 0},
      {q: "She regrets ___ rude.", o: ["being", "to be", "be"], c: 0},
      {q: "We risk ___ the game.", o: ["losing", "to lose", "lose"], c: 0},
      {q: "He delayed ___ for weeks.", o: ["answering", "to answer", "answer"], c: 0}
    ]
  },
  {
    level: 'B1',
    id: 41,
    title: 'Reported speech — declaraciones',
    description: 'She said she was happy. He told me he would help.',
    questions: [
      {q: "She said ___ was happy.", o: ["she", "I", "you"], c: 0},
      {q: "He told me ___ would help.", o: ["he", "I", "you"], c: 0},
      {q: "They explained ___ couldn't come.", o: ["they", "I", "we"], c: 0},
      {q: "I mentioned ___ was tired.", o: ["I", "you", "he"], c: 0},
      {q: "She admitted ___ had lied.", o: ["she", "I", "you"], c: 0},
      {q: "He claimed ___ had won.", o: ["he", "I", "they"], c: 0},
      {q: "They insisted ___ were right.", o: ["they", "I", "you"], c: 0},
      {q: "I explained ___ couldn't attend.", o: ["I", "you", "he"], c: 0},
      {q: "She announced ___ was pregnant.", o: ["she", "I", "you"], c: 0},
      {q: "He complained ___ had no time.", o: ["he", "I", "you"], c: 0},
      {q: "They reported ___ had seen nothing.", o: ["they", "I", "we"], c: 0},
      {q: "I suggested ___ should wait.", o: ["we", "I", "you"], c: 0},
      {q: "She promised ___ would return.", o: ["she", "I", "you"], c: 0},
      {q: "He warned ___ would be dangerous.", o: ["it", "I", "you"], c: 0},
      {q: "They denied ___ had taken anything.", o: ["they", "I", "we"], c: 0},
      {q: "I stated ___ had finished.", o: ["I", "you", "he"], c: 0},
      {q: "She claimed ___ had never seen him.", o: ["she", "I", "you"], c: 0},
      {q: "He assured ___ everything would be fine.", o: ["me/us", "him", "you"], c: 0},
      {q: "They declared ___ were innocent.", o: ["they", "I", "we"], c: 0},
      {q: "I revealed ___ had been lying.", o: ["I", "you", "he"], c: 0}
    ]
  },
  {
    level: 'B1',
    id: 42,
    title: 'Propósito, causa y contraste',
    description: 'in order to, so that, because, since, although, despite.',
    questions: [
      {q: "She studied hard ___ pass the exam.", o: ["in order to", "because", "although"], c: 0},
      {q: "He arrived late ___ the traffic.", o: ["because of", "in order to", "although"], c: 0},
      {q: "___ he was tired, he continued working.", o: ["Although", "Because", "In order to"], c: 0},
      {q: "We went to the beach ___ have fun.", o: ["to", "because", "although"], c: 0},
      {q: "She couldn't attend ___ she was sick.", o: ["because", "in order to", "although"], c: 0},
      {q: "___ his injury, he played the game.", o: ["Despite", "Because", "In order to"], c: 0},
      {q: "They worked all night ___ finish on time.", o: ["so that", "because", "although"], c: 0},
      {q: "I left early ___ avoid traffic.", o: ["to", "because", "although"], c: 0},
      {q: "___ the weather, we canceled the event.", o: ["Because of", "In order to", "Although"], c: 0},
      {q: "He studied ___ understand the material.", o: ["so as to", "because", "although"], c: 0},
      {q: "She failed ___ didn't study.", o: ["because she", "in order to", "although"], c: 0},
      {q: "___ being old, the house is beautiful.", o: ["Although", "Because", "In order to"], c: 0},
      {q: "We saved money ___ buy a house.", o: ["so that we could", "because", "although"], c: 0},
      {q: "I apologized ___ hurt her feelings.", o: ["because I had", "in order to", "although"], c: 0},
      {q: "___ his wealth, he was unhappy.", o: ["Despite", "Because", "In order to"], c: 0},
      {q: "She worked ___ reach her goals.", o: ["to", "because", "although"], c: 0},
      {q: "He moved ___ the opportunities were better there.", o: ["because", "in order to", "although"], c: 0},
      {q: "___ the difficulty, they succeeded.", o: ["Despite", "Because", "In order to"], c: 0},
      {q: "We trained hard ___ be ready.", o: ["so as to", "because", "although"], c: 0},
      {q: "I stayed quiet ___ cause trouble.", o: ["so as not to", "because", "although"], c: 0}
    ]
  },
  {
    level: 'B1',
    id: 43,
    title: 'Cuantificadores avanzados',
    description: 'several, a few, quite a lot, plenty of, a considerable amount of.',
    questions: [
      {q: "There are ___ people in the room.", o: ["quite a few", "a lot", "several"], c: 0},
      {q: "He has ___ experience in this field.", o: ["considerable", "several years of", "a lot of"], c: 0},
      {q: "I have ___ reasons to believe this.", o: ["several", "a lot", "plenty of"], c: 0},
      {q: "There is ___ food for everyone.", o: ["plenty of", "quite a", "several"], c: 0},
      {q: "She has ___ friends.", o: ["quite a lot of", "several", "many"], c: 0},
      {q: "There are ___ options available.", o: ["multiple", "quite a few", "a lot"], c: 0},
      {q: "He has ___ evidence.", o: ["substantial", "quite a", "several"], c: 0},
      {q: "I have only ___ time left.", o: ["a little", "several", "quite a lot"], c: 0},
      {q: "There is ___ paperwork to complete.", o: ["considerable", "quite a", "several"], c: 0},
      {q: "She has ___ talents.", o: ["numerous", "quite a few", "a lot"], c: 0},
      {q: "There are ___ reasons for this.", o: ["manifold", "quite a few", "a lot"], c: 0},
      {q: "He has ___ resources.", o: ["limited", "quite a", "several"], c: 0},
      {q: "I have ___ of those items.", o: ["a large number", "quite a", "several"], c: 0},
      {q: "There is ___ space in this room.", o: ["ample", "quite a", "several"], c: 0},
      {q: "She has ___ responsibilities.", o: ["many", "quite a few", "a lot"], c: 0},
      {q: "There are ___ issues to address.", o: ["numerous", "quite a few", "a lot"], c: 0},
      {q: "He has ___ achievements.", o: ["remarkable", "quite a few", "a lot"], c: 0},
      {q: "I have only ___ doubts.", o: ["marginal", "quite a", "several"], c: 0},
      {q: "There is ___ scope for improvement.", o: ["considerable", "quite a", "several"], c: 0},
      {q: "She has ___ opportunities.", o: ["boundless", "quite a few", "a lot"], c: 0}
    ]
  },
  {
    level: 'B1',
    id: 44,
    title: 'Futuro continuo y futuro perfecto',
    description: 'will be working, will have finished.',
    questions: [
      {q: "I ___ at 9 tomorrow morning.", o: ["will be working", "work", "will work"], c: 0},
      {q: "She ___ by next month.", o: ["will have graduated", "will graduate", "graduates"], c: 0},
      {q: "They ___ when you arrive.", o: ["will be sleeping", "will sleep", "sleep"], c: 0},
      {q: "He ___ for 10 hours by midnight.", o: ["will have worked", "will work", "works"], c: 0},
      {q: "We ___ when the game starts.", o: ["will be watching", "will watch", "watch"], c: 0},
      {q: "I ___ this project by Friday.", o: ["will have completed", "will complete", "complete"], c: 0},
      {q: "She ___ for 5 years next January.", o: ["will have lived", "will live", "lives"], c: 0},
      {q: "They ___ dinner at 7.", o: ["will be eating", "will eat", "eat"], c: 0},
      {q: "He ___ all the books by summer.", o: ["will have read", "will read", "reads"], c: 0},
      {q: "You ___ when I call.", o: ["will be studying", "will study", "study"], c: 0},
      {q: "I ___ for you at the station.", o: ["will be waiting", "will wait", "wait"], c: 0},
      {q: "She ___ the house by next week.", o: ["will have painted", "will paint", "paints"], c: 0},
      {q: "They ___ their homework when we arrive.", o: ["will be doing", "will do", "do"], c: 0},
      {q: "He ___ his goals by the end of the year.", o: ["will have achieved", "will achieve", "achieves"], c: 0},
      {q: "We ___ at the beach tomorrow afternoon.", o: ["will be swimming", "will swim", "swim"], c: 0},
      {q: "I ___ everything by then.", o: ["will have forgotten", "will forget", "forget"], c: 0},
      {q: "She ___ her new job for a month by then.", o: ["will have started", "will start", "starts"], c: 0},
      {q: "They ___ in the meeting when you arrive.", o: ["will be discussing", "will discuss", "discuss"], c: 0},
      {q: "He ___ his training by next summer.", o: ["will have completed", "will complete", "completes"], c: 0},
      {q: "You ___ your tickets by tomorrow.", o: ["will have bought", "will buy", "buy"], c: 0}
    ]
  },
  {
    level: 'B1',
    id: 45,
    title: 'Phrasal verbs frecuentes',
    description: 'put up with, run into, look after, break down.',
    questions: [
      {q: "I can't ___ his behavior anymore.", o: ["put up with", "put in", "put on"], c: 0},
      {q: "She ___ her old friend at the market.", o: ["ran into", "ran out of", "ran away"], c: 0},
      {q: "They ___ the project last week.", o: ["turned down", "turned on", "turned into"], c: 0},
      {q: "He ___ his boss.", o: ["looks up to", "looks after", "looks into"], c: 0},
      {q: "We need to ___ this issue.", o: ["look into", "look after", "look up to"], c: 0},
      {q: "I ___ my studies.", o: ["give up", "give in", "give away"], c: 0},
      {q: "She ___ all night.", o: ["stayed up", "stayed out", "stayed in"], c: 0},
      {q: "They ___ the meeting.", o: ["put off", "put up", "put in"], c: 0},
      {q: "He ___ his coat.", o: ["took off", "took on", "took after"], c: 0},
      {q: "We ___ the problem immediately.", o: ["dealt with", "dealt in", "dealt out"], c: 0},
      {q: "I ___ the light.", o: ["turned on", "turned off", "turned into"], c: 0},
      {q: "She ___ her children while at work.", o: ["looks after", "looks up to", "looks into"], c: 0},
      {q: "They ___ the competition.", o: ["brought on", "brought up", "brought in"], c: 0},
      {q: "He ___ his father.", o: ["takes after", "takes on", "takes over"], c: 0},
      {q: "We must ___ smoking.", o: ["give up", "give in", "give out"], c: 0},
      {q: "I ___ with the stress.", o: ["cope with", "cope in", "cope on"], c: 0},
      {q: "She ___ her suitcase.", o: ["packed up", "packed in", "packed on"], c: 0},
      {q: "They ___ the fire quickly.", o: ["put out", "put up", "put in"], c: 0},
      {q: "He will ___ his business to his son.", o: ["hand over", "hand in", "hand out"], c: 0},
      {q: "We ___ the trip because of the weather.", o: ["called off", "called on", "called up"], c: 0}
    ]
  },
  {
    level: 'B1',
    id: 46,
    title: 'Wish + pasado simple / could',
    description: 'I wish I were rich. I wish I could fly.',
    questions: [
      {q: "I wish I ___ rich.", o: ["were", "was", "am"], c: 0},
      {q: "She wishes she ___ speak Italian.", o: ["could", "can", "would"], c: 0},
      {q: "He wishes he ___ more time.", o: ["had", "has", "would have"], c: 0},
      {q: "I wish I ___ that yesterday.", o: ["hadn't said", "didn't say", "wouldn't say"], c: 0},
      {q: "They wish they ___ live in Paris.", o: ["could", "can", "would"], c: 0},
      {q: "I wish I ___ taller.", o: ["were", "was", "am"], c: 0},
      {q: "She wishes she ___ more confident.", o: ["were", "was", "is"], c: 0},
      {q: "He wishes he ___ attend the event.", o: ["could", "can", "would"], c: 0},
      {q: "I wish it ___ raining.", o: ["weren't", "wasn't", "isn't"], c: 0},
      {q: "They wish they ___ meet him.", o: ["could", "can", "would"], c: 0},
      {q: "I wish I ___ made that mistake.", o: ["hadn't", "didn't", "wouldn't"], c: 0},
      {q: "She wishes she ___ younger.", o: ["were", "was", "is"], c: 0},
      {q: "He wishes he ___ known the truth.", o: ["had", "has", "would have"], c: 0},
      {q: "I wish I ___ visit you more often.", o: ["could", "can", "would"], c: 0},
      {q: "They wish they ___ understand better.", o: ["could", "can", "would"], c: 0},
      {q: "I wish you ___ here with us.", o: ["were", "was", "are"], c: 0},
      {q: "She wishes she ___ say no.", o: ["could", "can", "would"], c: 0},
      {q: "He wishes he ___ started earlier.", o: ["had", "has", "would have"], c: 0},
      {q: "I wish this ___ true.", o: ["were", "was", "is"], c: 0},
      {q: "They wish they ___ different parents.", o: ["had", "have", "would have"], c: 0}
    ]
  },
  {
    level: 'B1',
    id: 47,
    title: 'Conectores discursivos',
    description: 'furthermore, in addition, however, moreover, nevertheless.',
    questions: [
      {q: "___, we need more funding.", o: ["Furthermore", "However", "Instead"], c: 0},
      {q: "He is talented. ___, he is very hardworking.", o: ["Moreover", "However", "Instead"], c: 0},
      {q: "She was late; ___, she had a good excuse.", o: ["however", "moreover", "therefore"], c: 0},
      {q: "___ what happened, she remained calm.", o: ["Despite", "In addition", "Furthermore"], c: 0},
      {q: "The plan was risky. ___, it was the only option.", o: ["Nevertheless", "Furthermore", "Moreover"], c: 0},
      {q: "___ the above, we have budget constraints.", o: ["In addition to", "Moreover", "Furthermore"], c: 0},
      {q: "He didn't prepare. ___, he passed the exam.", o: ["Nevertheless", "Moreover", "Furthermore"], c: 0},
      {q: "She is intelligent. ___, she is kind.", o: ["In addition", "However", "Instead"], c: 0},
      {q: "___ all this, the situation improved.", o: ["Despite", "Furthermore", "Moreover"], c: 0},
      {q: "The weather was bad. ___, we enjoyed ourselves.", o: ["However", "Moreover", "Furthermore"], c: 0},
      {q: "___, he made significant progress.", o: ["Thereafter", "Consequently", "Otherwise"], c: 1},
      {q: "They were poor. ___, they were happy.", o: ["Nevertheless", "However", "Moreover"], c: 0},
      {q: "He worked hard. ___, he achieved his goal.", o: ["Consequently", "However", "Moreover"], c: 0},
      {q: "___ his intelligence, he failed.", o: ["Despite", "Furthermore", "Moreover"], c: 0},
      {q: "She spoke well. ___, she was nervous.", o: ["However", "Furthermore", "Moreover"], c: 0},
      {q: "___, the facts were clear.", o: ["Nonetheless", "Furthermore", "Moreover"], c: 0},
      {q: "He was sick. ___, he came to work.", o: ["Nevertheless", "However", "Instead"], c: 0},
      {q: "___  his efforts, he failed.", o: ["Despite", "Furthermore", "Moreover"], c: 0},
      {q: "She was experienced. ___, she made mistakes.", o: ["However", "Furthermore", "Moreover"], c: 0},
      {q: "They fought. ___, they remained friends.", o: ["Nevertheless", "However", "Moreover"], c: 0}
    ]
  },
  {
    level: 'B1',
    id: 48,
    title: 'Preguntas indirectas',
    description: 'Do you know where he lives? I wonder if she is coming.',
    questions: [
      {q: "Do you know ___?", o: ["where he lives", "where does he live", "where he lived"], c: 0},
      {q: "I wonder ___.", o: ["if she is coming", "if is she coming", "if she comes"], c: 0},
      {q: "Can you tell me ___?", o: ["what time it is", "what time is it", "what time it was"], c: 0},
      {q: "Do you know ___?", o: ["why he left", "why did he leave", "why he leaves"], c: 0},
      {q: "I'd like to know ___.", o: ["how much it costs", "how much does it cost", "how much it costed"], c: 0},
      {q: "Could you tell me ___?", o: ["where the bathroom is", "where is the bathroom", "where the bathroom was"], c: 0},
      {q: "Do you know ___?", o: ["when she arrives", "when does she arrive", "when she arrived"], c: 0},
      {q: "I'm wondering ___.", o: ["if he will help", "if will he help", "if he helps"], c: 0},
      {q: "Could you explain ___?", o: ["how this works", "how does this work", "how this worked"], c: 0},
      {q: "Do you know ___?", o: ["who she is", "who is she", "who she was"], c: 0},
      {q: "I'm curious about ___.", o: ["what he said", "what did he say", "what he says"], c: 0},
      {q: "Can you tell me ___?", o: ["if he's coming", "if is he coming", "if he comes"], c: 0},
      {q: "Do you know ___?", o: ["how far it is", "how far is it", "how far it was"], c: 0},
      {q: "I'd like to know ___.", o: ["what you think", "what do you think", "what you are thinking"], c: 0},
      {q: "Could you tell me ___?", o: ["how much longer it will take", "how much longer will it take", "how much longer it takes"], c: 0},
      {q: "Do you know ___?", o: ["what her name is", "what is her name", "what her name was"], c: 0},
      {q: "I'm wondering ___.", o: ["why he didn't call", "why didn't he call", "why he doesn't call"], c: 0},
      {q: "Can you tell me ___?", o: ["when the meeting starts", "when does the meeting start", "when the meeting started"], c: 0},
      {q: "Do you know ___?", o: ["if we should wait", "if should we wait", "if we wait"], c: 0},
      {q: "I'd like to know ___.", o: ["what happened next", "what does happen next", "what happened then"], c: 0}
    ]
  },

  // ========== B2 (15 TEMAS) ==========
  {
    level: 'B2',
    id: 49,
    title: 'Condicional tipo 3',
    description: 'If I had known, I would have told you. Situación imposible en el pasado.',
    questions: [
      {q: "If I ___ earlier, I would have arrived on time.", o: ["had left", "left", "would leave"], c: 0},
      {q: "She ___ if she had studied.", o: ["would have passed", "would pass", "passes"], c: 0},
      {q: "If they ___ about it, they would have reacted differently.", o: ["had known", "knew", "would know"], c: 0},
      {q: "We ___ if we had seen the warning.", o: ["would have stopped", "would stop", "stop"], c: 0},
      {q: "If I ___ you,